version: "3.9"

services:
  backend:
    build:
      context: ./pygeoapi
      dockerfile: Dockerfile
    container_name: geo-backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data:ro

  frontend:
    build: ./frontend
    container_name: geo-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
