version: '3.9'
services:
  pygeoapi:
    build:
      context: .
      dockerfile: pygeoapi/Dockerfile
    ports:
      - "5000:5000"

  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - pygeoapi
