apiVersion: apps/v1
kind: Deployment
metadata:
  name: pygeoapi
  labels:
    app: pygeoapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pygeoapi
  template:
    metadata:
      labels:
        app: pygeoapi
    spec:
      containers:
        - name: pygeoapi
          image: ghcr.io/yejiyang/pygeoapi-w-global-tsunami-data:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "[ -f /tmp/health/init_complete ] && curl -s --max-time 10 http://localhost:5000/ > /dev/null"
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 3
          env:
            - name: PYGEOAPI_CONFIG
              value: /pygeoapi/local.config.yml
            - name: PYGEOAPI_OPENAPI
              value: /tmp/openapi.yml
            - name: CONTAINER_NAME
              value: pygeoapi
            - name: CONTAINER_HOST
              value: 0.0.0.0
            - name: CONTAINER_PORT
              value: "5000"
            - name: PYGEOAPI_SERVER_URL
              # The URL that users will access your service through - adjust based on your Kubernetes setup
              value: "https://your-domain.com/api" # Replace with your actual domain and include /api path
---
apiVersion: v1
kind: Service
metadata:
  name: pygeoapi
spec:
  selector:
    app: pygeoapi
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/yejiyang/global-tsunami-risk-map-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              # The URL where the backend API is accessible from frontend clients
              value: "https://tsunami.jye.no/api"
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
# Ingress controller configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geospatial-ingress
  annotations:
    # Add appropriate annotations for your ingress controller
    # For example, for nginx:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: your-domain.com # Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: pygeoapi
                port:
                  number: 80
