server:
  url: http://localhost:5000
  mimetype: application/json
  encoding: utf-8
  language: en
  cors: true

logging:
  level: INFO

resources:
  points:
    type: collection
    title: Sample Points
    description: Simple point data
    keywords:
      - sample
      - points
    provider:
      type: feature
      name: GeoJSON
      data: /data/points.geojson
      id_field: name
    bbox: [-180,-90,180,90]
