server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: http://localhost:5000/
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en-US
  cors: true
  pretty_print: true
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'

logging:
    level: DEBUG
    logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title: Geospatial Dataset Publishing API
        description: API for publishing and accessing geospatial datasets
        keywords:
            - geospatial
            - data
            - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://localhost:5000
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: http://localhost:5000
    contact:
        name: Admin
        position: Admin
        email: admin@example.org

resources:
    points:
        type: collection
        title: Global Hazard Points
        description: Global hazard points data in GeoJSON format
        keywords:
            - points
            - hazards
            - global
        links:
            - type: application/geo+json
              rel: items
              title: Global Hazard Points (GeoJSON)
              href: http://localhost:5000/collections/points/items
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: GeoJSON
              data: ../data/points.geojson
              id_field: id

    hazard_points_fgb:
        type: collection
        title: Global Hazard Points (FlatGeobuf)
        description: Global hazard points data in FlatGeobuf format
        keywords:
            - points
            - hazards
            - global
        links:
            - type: application/geo+json
              rel: items
              title: Global Hazard Points (FlatGeobuf)
              href: http://localhost:5000/collections/hazard_points_fgb/items
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: feature
              name: OGR
              data:
                source_type: FlatGeobuf
                source: ../data/global-hazard-points.fgb
              layer: GlobalHazardPoints
              id_field: id
        tiles:
            type: mvt
            link_rel: tiles
            zoom:
                min: 0
                max: 14
